// Code generated by go generate ./acp; DO NOT EDIT.

package acp

import "encoding/json"

const ProtocolVersionNumber = 1

const (
	AgentMethodAuthenticate           = "authenticate"
	AgentMethodInitialize             = "initialize"
	AgentMethodLogout                 = "logout"
	AgentMethodSessionCancel          = "session/cancel"
	AgentMethodSessionClose           = "session/close"
	AgentMethodSessionList            = "session/list"
	AgentMethodSessionLoad            = "session/load"
	AgentMethodSessionNew             = "session/new"
	AgentMethodSessionPrompt          = "session/prompt"
	AgentMethodSessionResume          = "session/resume"
	AgentMethodSessionSetConfigOption = "session/set_config_option"
	AgentMethodSessionSetMode         = "session/set_mode"
)

const (
	ClientMethodElicitationComplete      = "elicitation/complete"
	ClientMethodElicitationCreate        = "elicitation/create"
	ClientMethodFSReadTextFile           = "fs/read_text_file"
	ClientMethodFSWriteTextFile          = "fs/write_text_file"
	ClientMethodSessionRequestPermission = "session/request_permission"
	ClientMethodSessionUpdate            = "session/update"
	ClientMethodTerminalCreate           = "terminal/create"
	ClientMethodTerminalKill             = "terminal/kill"
	ClientMethodTerminalOutput           = "terminal/output"
	ClientMethodTerminalRelease          = "terminal/release"
	ClientMethodTerminalWaitForExit      = "terminal/wait_for_exit"
)

type AgentAuthCapabilities struct {
	Meta   map[string]any      `json:"_meta,omitempty"`
	Logout *LogoutCapabilities `json:"logout,omitempty"`
}

type AgentCapabilities struct {
	Meta                map[string]any         `json:"_meta,omitempty"`
	Auth                *AgentAuthCapabilities `json:"auth,omitempty"`
	LoadSession         bool                   `json:"loadSession,omitempty"`
	MCPCapabilities     *MCPCapabilities       `json:"mcpCapabilities,omitempty"`
	PromptCapabilities  *PromptCapabilities    `json:"promptCapabilities,omitempty"`
	SessionCapabilities *SessionCapabilities   `json:"sessionCapabilities,omitempty"`
}

type AgentNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type AgentRequest struct {
	ID     RequestID       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type AgentResponse json.RawMessage

type Annotations struct {
	Meta         map[string]any `json:"_meta,omitempty"`
	Audience     []Role         `json:"audience,omitempty"`
	LastModified string         `json:"lastModified,omitempty"`
	Priority     float64        `json:"priority,omitempty"`
}

type AudioContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
}

type AuthMethod AuthMethodAgent

type AuthMethodAgent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description string         `json:"description,omitempty"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
}

type AuthenticateRequest struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MethodID string         `json:"methodId"`
}

type AuthenticateResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type AvailableCommand struct {
	Meta        map[string]any         `json:"_meta,omitempty"`
	Description string                 `json:"description"`
	Input       *AvailableCommandInput `json:"input,omitempty"`
	Name        string                 `json:"name"`
}

type AvailableCommandInput UnstructuredCommandInput

type AvailableCommandsUpdate struct {
	Meta              map[string]any     `json:"_meta,omitempty"`
	AvailableCommands []AvailableCommand `json:"availableCommands"`
}

type BlobResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	Blob     string         `json:"blob"`
	MimeType string         `json:"mimeType,omitempty"`
	URI      string         `json:"uri"`
}

type BooleanPropertySchema struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Default     bool           `json:"default,omitempty"`
	Description string         `json:"description,omitempty"`
	Title       string         `json:"title,omitempty"`
}

type CancelNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
}

type ClientCapabilities struct {
	Meta        map[string]any           `json:"_meta,omitempty"`
	Elicitation *ElicitationCapabilities `json:"elicitation,omitempty"`
	FS          *FileSystemCapabilities  `json:"fs,omitempty"`
	Terminal    bool                     `json:"terminal,omitempty"`
}

type ClientNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type ClientRequest struct {
	ID     RequestID       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type ClientResponse json.RawMessage

type CloseSessionRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
}

type CloseSessionResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type CompleteElicitationNotification struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	ElicitationID ElicitationID  `json:"elicitationId"`
}

type ConfigOptionUpdate struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

type Content struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content ContentBlock   `json:"content"`
}

type ContentBlock json.RawMessage

type ContentChunk struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content ContentBlock   `json:"content"`
}

type CreateElicitationRequest struct {
	Meta            map[string]any     `json:"_meta,omitempty"`
	Message         string             `json:"message"`
	Mode            string             `json:"mode"`
	RequestID       *RequestID         `json:"requestId,omitempty"`
	RequestedSchema *ElicitationSchema `json:"requestedSchema,omitempty"`
	SessionID       *SessionID         `json:"sessionId,omitempty"`
	ToolCallID      *ToolCallID        `json:"toolCallId,omitempty"`
}

type CreateElicitationResponse struct {
	Meta    map[string]any                     `json:"_meta,omitempty"`
	Action  string                             `json:"action"`
	Content map[string]ElicitationContentValue `json:"content,omitempty"`
}

type CreateTerminalRequest struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Args            []string       `json:"args,omitempty"`
	Command         string         `json:"command"`
	Cwd             string         `json:"cwd,omitempty"`
	Env             []EnvVariable  `json:"env,omitempty"`
	OutputByteLimit int            `json:"outputByteLimit,omitempty"`
	SessionID       SessionID      `json:"sessionId"`
}

type CreateTerminalResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

type CurrentModeUpdate struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	CurrentModeID SessionModeID  `json:"currentModeId"`
}

type Diff struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	NewText string         `json:"newText"`
	OldText string         `json:"oldText,omitempty"`
	Path    string         `json:"path"`
}

type ElicitationAcceptAction struct {
	Content map[string]ElicitationContentValue `json:"content,omitempty"`
}

type ElicitationCapabilities struct {
	Meta map[string]any               `json:"_meta,omitempty"`
	Form *ElicitationFormCapabilities `json:"form,omitempty"`
	URL  *ElicitationURLCapabilities  `json:"url,omitempty"`
}

type ElicitationContentValue = json.RawMessage

type ElicitationFormCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type ElicitationFormMode struct {
	RequestID       *RequestID        `json:"requestId,omitempty"`
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
	SessionID       *SessionID        `json:"sessionId,omitempty"`
	ToolCallID      *ToolCallID       `json:"toolCallId,omitempty"`
}

type ElicitationID string

type ElicitationPropertySchema struct {
	Meta        map[string]any    `json:"_meta,omitempty"`
	Default     json.RawMessage   `json:"default,omitempty"`
	Description string            `json:"description,omitempty"`
	Enum        []string          `json:"enum,omitempty"`
	Format      *StringFormat     `json:"format,omitempty"`
	Items       *MultiSelectItems `json:"items,omitempty"`
	MaxItems    int               `json:"maxItems,omitempty"`
	MaxLength   int               `json:"maxLength,omitempty"`
	Maximum     json.RawMessage   `json:"maximum,omitempty"`
	MinItems    int               `json:"minItems,omitempty"`
	MinLength   int               `json:"minLength,omitempty"`
	Minimum     json.RawMessage   `json:"minimum,omitempty"`
	OneOf       []EnumOption      `json:"oneOf,omitempty"`
	Pattern     string            `json:"pattern,omitempty"`
	Title       string            `json:"title,omitempty"`
	Type        string            `json:"type"`
}

type ElicitationRequestScope struct {
	RequestID RequestID `json:"requestId"`
}

type ElicitationSchema struct {
	Meta        map[string]any                       `json:"_meta,omitempty"`
	Description string                               `json:"description,omitempty"`
	Properties  map[string]ElicitationPropertySchema `json:"properties,omitempty"`
	Required    []string                             `json:"required,omitempty"`
	Title       string                               `json:"title,omitempty"`
	Type        *ElicitationSchemaType               `json:"type,omitempty"`
}

type ElicitationSchemaType string

const (
	ElicitationSchemaTypeObject ElicitationSchemaType = "object"
)

type ElicitationSessionScope struct {
	SessionID  SessionID   `json:"sessionId"`
	ToolCallID *ToolCallID `json:"toolCallId,omitempty"`
}

type ElicitationStringType string

const (
	ElicitationStringTypeString ElicitationStringType = "string"
)

type ElicitationURLCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type ElicitationURLMode struct {
	ElicitationID ElicitationID `json:"elicitationId"`
	RequestID     *RequestID    `json:"requestId,omitempty"`
	SessionID     *SessionID    `json:"sessionId,omitempty"`
	ToolCallID    *ToolCallID   `json:"toolCallId,omitempty"`
	URL           string        `json:"url"`
}

type EmbeddedResource struct {
	Meta        map[string]any           `json:"_meta,omitempty"`
	Annotations *Annotations             `json:"annotations,omitempty"`
	Resource    EmbeddedResourceResource `json:"resource"`
}

type EmbeddedResourceResource json.RawMessage

type EnumOption struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Const string         `json:"const"`
	Title string         `json:"title"`
}

type EnvVariable struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

type Error struct {
	Code    ErrorCode       `json:"code"`
	Data    json.RawMessage `json:"data,omitempty"`
	Message string          `json:"message"`
}

type ErrorCode int

const (
	ErrorCode32700 ErrorCode = -32700
	ErrorCode32600 ErrorCode = -32600
	ErrorCode32601 ErrorCode = -32601
	ErrorCode32602 ErrorCode = -32602
	ErrorCode32603 ErrorCode = -32603
	ErrorCode32000 ErrorCode = -32000
	ErrorCode32002 ErrorCode = -32002
)

type ExtNotification json.RawMessage

type ExtRequest json.RawMessage

type ExtResponse json.RawMessage

type FileSystemCapabilities struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	ReadTextFile  bool           `json:"readTextFile,omitempty"`
	WriteTextFile bool           `json:"writeTextFile,omitempty"`
}

type HTTPHeader struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

type ImageContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
	URI         string         `json:"uri,omitempty"`
}

type Implementation struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Name    string         `json:"name"`
	Title   string         `json:"title,omitempty"`
	Version string         `json:"version"`
}

type InitializeRequest struct {
	Meta               map[string]any      `json:"_meta,omitempty"`
	ClientCapabilities *ClientCapabilities `json:"clientCapabilities,omitempty"`
	ClientInfo         *Implementation     `json:"clientInfo,omitempty"`
	ProtocolVersion    ProtocolVersion     `json:"protocolVersion"`
}

type InitializeResponse struct {
	Meta              map[string]any     `json:"_meta,omitempty"`
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitempty"`
	AgentInfo         *Implementation    `json:"agentInfo,omitempty"`
	AuthMethods       []AuthMethod       `json:"authMethods,omitempty"`
	ProtocolVersion   ProtocolVersion    `json:"protocolVersion"`
}

type IntegerPropertySchema struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Default     int64          `json:"default,omitempty"`
	Description string         `json:"description,omitempty"`
	Maximum     int64          `json:"maximum,omitempty"`
	Minimum     int64          `json:"minimum,omitempty"`
	Title       string         `json:"title,omitempty"`
}

type KillTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

type KillTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type ListSessionsRequest struct {
	Meta   map[string]any `json:"_meta,omitempty"`
	Cursor string         `json:"cursor,omitempty"`
	Cwd    string         `json:"cwd,omitempty"`
}

type ListSessionsResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	NextCursor string         `json:"nextCursor,omitempty"`
	Sessions   []SessionInfo  `json:"sessions"`
}

type LoadSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
	SessionID  SessionID      `json:"sessionId"`
}

type LoadSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
}

type LogoutCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type LogoutRequest struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type LogoutResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type MCPCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
	HTTP bool           `json:"http,omitempty"`
	SSE  bool           `json:"sse,omitempty"`
}

type MCPServer json.RawMessage

type MCPServerHTTP struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HTTPHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

type MCPServerSSE struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HTTPHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

type MCPServerStdio struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Args    []string       `json:"args"`
	Command string         `json:"command"`
	Env     []EnvVariable  `json:"env"`
	Name    string         `json:"name"`
}

type MultiSelectItems struct {
	Meta  map[string]any         `json:"_meta,omitempty"`
	AnyOf []EnumOption           `json:"anyOf,omitempty"`
	Enum  []string               `json:"enum,omitempty"`
	Type  *ElicitationStringType `json:"type,omitempty"`
}

type MultiSelectPropertySchema struct {
	Meta        map[string]any   `json:"_meta,omitempty"`
	Default     []string         `json:"default,omitempty"`
	Description string           `json:"description,omitempty"`
	Items       MultiSelectItems `json:"items"`
	MaxItems    int              `json:"maxItems,omitempty"`
	MinItems    int              `json:"minItems,omitempty"`
	Title       string           `json:"title,omitempty"`
}

type NewSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
}

type NewSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
	SessionID     SessionID             `json:"sessionId"`
}

type NumberPropertySchema struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Default     float64        `json:"default,omitempty"`
	Description string         `json:"description,omitempty"`
	Maximum     float64        `json:"maximum,omitempty"`
	Minimum     float64        `json:"minimum,omitempty"`
	Title       string         `json:"title,omitempty"`
}

type PermissionOption struct {
	Meta     map[string]any       `json:"_meta,omitempty"`
	Kind     PermissionOptionKind `json:"kind"`
	Name     string               `json:"name"`
	OptionID PermissionOptionID   `json:"optionId"`
}

type PermissionOptionID string

type PermissionOptionKind string

const (
	PermissionOptionKindAllowOnce    PermissionOptionKind = "allow_once"
	PermissionOptionKindAllowAlways  PermissionOptionKind = "allow_always"
	PermissionOptionKindRejectOnce   PermissionOptionKind = "reject_once"
	PermissionOptionKindRejectAlways PermissionOptionKind = "reject_always"
)

type Plan struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Entries []PlanEntry    `json:"entries"`
}

type PlanEntry struct {
	Meta     map[string]any    `json:"_meta,omitempty"`
	Content  string            `json:"content"`
	Priority PlanEntryPriority `json:"priority"`
	Status   PlanEntryStatus   `json:"status"`
}

type PlanEntryPriority string

const (
	PlanEntryPriorityHigh   PlanEntryPriority = "high"
	PlanEntryPriorityMedium PlanEntryPriority = "medium"
	PlanEntryPriorityLow    PlanEntryPriority = "low"
)

type PlanEntryStatus string

const (
	PlanEntryStatusPending    PlanEntryStatus = "pending"
	PlanEntryStatusInProgress PlanEntryStatus = "in_progress"
	PlanEntryStatusCompleted  PlanEntryStatus = "completed"
)

type PromptCapabilities struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Audio           bool           `json:"audio,omitempty"`
	EmbeddedContext bool           `json:"embeddedContext,omitempty"`
	Image           bool           `json:"image,omitempty"`
}

type PromptRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Prompt    []ContentBlock `json:"prompt"`
	SessionID SessionID      `json:"sessionId"`
}

type PromptResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	StopReason StopReason     `json:"stopReason"`
}

type ProtocolVersion uint16

type ReadTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Limit     int            `json:"limit,omitempty"`
	Line      int            `json:"line,omitempty"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

type ReadTextFileResponse struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content string         `json:"content"`
}

type ReleaseTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

type ReleaseTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type RequestID json.RawMessage

type RequestPermissionOutcome json.RawMessage

type RequestPermissionRequest struct {
	Meta      map[string]any     `json:"_meta,omitempty"`
	Options   []PermissionOption `json:"options"`
	SessionID SessionID          `json:"sessionId"`
	ToolCall  ToolCallUpdate     `json:"toolCall"`
}

type RequestPermissionResponse struct {
	Meta    map[string]any           `json:"_meta,omitempty"`
	Outcome RequestPermissionOutcome `json:"outcome"`
}

type ResourceLink struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Description string         `json:"description,omitempty"`
	MimeType    string         `json:"mimeType,omitempty"`
	Name        string         `json:"name"`
	Size        int64          `json:"size,omitempty"`
	Title       string         `json:"title,omitempty"`
	URI         string         `json:"uri"`
}

type ResumeSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
}

type ResumeSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
}

type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

type SelectedPermissionOutcome struct {
	Meta     map[string]any     `json:"_meta,omitempty"`
	OptionID PermissionOptionID `json:"optionId"`
}

type SessionCapabilities struct {
	Meta   map[string]any             `json:"_meta,omitempty"`
	Close  *SessionCloseCapabilities  `json:"close,omitempty"`
	List   *SessionListCapabilities   `json:"list,omitempty"`
	Resume *SessionResumeCapabilities `json:"resume,omitempty"`
}

type SessionCloseCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionConfigGroupID string

type SessionConfigID string

type SessionConfigOption struct {
	Meta        map[string]any               `json:"_meta,omitempty"`
	Category    *SessionConfigOptionCategory `json:"category,omitempty"`
	Description string                       `json:"description,omitempty"`
	ID          SessionConfigID              `json:"id"`
	Name        string                       `json:"name"`
}

type SessionConfigOptionCategory string

const (
	SessionConfigOptionCategoryMode         SessionConfigOptionCategory = "mode"
	SessionConfigOptionCategoryModel        SessionConfigOptionCategory = "model"
	SessionConfigOptionCategoryThoughtLevel SessionConfigOptionCategory = "thought_level"
)

type SessionConfigSelect struct {
	CurrentValue SessionConfigValueID       `json:"currentValue"`
	Options      SessionConfigSelectOptions `json:"options"`
}

type SessionConfigSelectGroup struct {
	Meta    map[string]any              `json:"_meta,omitempty"`
	Group   SessionConfigGroupID        `json:"group"`
	Name    string                      `json:"name"`
	Options []SessionConfigSelectOption `json:"options"`
}

type SessionConfigSelectOption struct {
	Meta        map[string]any       `json:"_meta,omitempty"`
	Description string               `json:"description,omitempty"`
	Name        string               `json:"name"`
	Value       SessionConfigValueID `json:"value"`
}

type SessionConfigSelectOptions json.RawMessage

type SessionConfigValueID string

type SessionID string

type SessionInfo struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Cwd       string         `json:"cwd"`
	SessionID SessionID      `json:"sessionId"`
	Title     string         `json:"title,omitempty"`
	UpdatedAt string         `json:"updatedAt,omitempty"`
}

type SessionInfoUpdate struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Title     string         `json:"title,omitempty"`
	UpdatedAt string         `json:"updatedAt,omitempty"`
}

type SessionListCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionMode struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description string         `json:"description,omitempty"`
	ID          SessionModeID  `json:"id"`
	Name        string         `json:"name"`
}

type SessionModeID string

type SessionModeState struct {
	Meta           map[string]any `json:"_meta,omitempty"`
	AvailableModes []SessionMode  `json:"availableModes"`
	CurrentModeID  SessionModeID  `json:"currentModeId"`
}

type SessionNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
	Update    SessionUpdate  `json:"update"`
}

type SessionResumeCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionUpdate json.RawMessage

type SetSessionConfigOptionRequest struct {
	Meta      map[string]any       `json:"_meta,omitempty"`
	ConfigID  SessionConfigID      `json:"configId"`
	SessionID SessionID            `json:"sessionId"`
	Value     SessionConfigValueID `json:"value"`
}

type SetSessionConfigOptionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

type SetSessionModeRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	ModeID    SessionModeID  `json:"modeId"`
	SessionID SessionID      `json:"sessionId"`
}

type SetSessionModeResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type StopReason string

const (
	StopReasonEndTurn         StopReason = "end_turn"
	StopReasonMaxTokens       StopReason = "max_tokens"
	StopReasonMaxTurnRequests StopReason = "max_turn_requests"
	StopReasonRefusal         StopReason = "refusal"
	StopReasonCancelled       StopReason = "cancelled"
)

type StringFormat string

const (
	StringFormatEmail    StringFormat = "email"
	StringFormatURI      StringFormat = "uri"
	StringFormatDate     StringFormat = "date"
	StringFormatDateTime StringFormat = "date-time"
)

type StringPropertySchema struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Default     string         `json:"default,omitempty"`
	Description string         `json:"description,omitempty"`
	Enum        []string       `json:"enum,omitempty"`
	Format      *StringFormat  `json:"format,omitempty"`
	MaxLength   int            `json:"maxLength,omitempty"`
	MinLength   int            `json:"minLength,omitempty"`
	OneOf       []EnumOption   `json:"oneOf,omitempty"`
	Pattern     string         `json:"pattern,omitempty"`
	Title       string         `json:"title,omitempty"`
}

type Terminal struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

type TerminalExitStatus struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode int            `json:"exitCode,omitempty"`
	Signal   string         `json:"signal,omitempty"`
}

type TerminalOutputRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

type TerminalOutputResponse struct {
	Meta       map[string]any      `json:"_meta,omitempty"`
	ExitStatus *TerminalExitStatus `json:"exitStatus,omitempty"`
	Output     string              `json:"output"`
	Truncated  bool                `json:"truncated"`
}

type TextContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Text        string         `json:"text"`
}

type TextResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MimeType string         `json:"mimeType,omitempty"`
	Text     string         `json:"text"`
	URI      string         `json:"uri"`
}

type TitledMultiSelectItems struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	AnyOf []EnumOption   `json:"anyOf"`
}

type ToolCall struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       *ToolKind          `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *ToolCallStatus    `json:"status,omitempty"`
	Title      string             `json:"title"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

type ToolCallContent = json.RawMessage

type ToolCallID string

type ToolCallLocation struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Line int            `json:"line,omitempty"`
	Path string         `json:"path"`
}

type ToolCallStatus string

const (
	ToolCallStatusPending    ToolCallStatus = "pending"
	ToolCallStatusInProgress ToolCallStatus = "in_progress"
	ToolCallStatusCompleted  ToolCallStatus = "completed"
	ToolCallStatusFailed     ToolCallStatus = "failed"
)

type ToolCallUpdate struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       *ToolKind          `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *ToolCallStatus    `json:"status,omitempty"`
	Title      string             `json:"title,omitempty"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

type ToolKind string

const (
	ToolKindRead       ToolKind = "read"
	ToolKindEdit       ToolKind = "edit"
	ToolKindDelete     ToolKind = "delete"
	ToolKindMove       ToolKind = "move"
	ToolKindSearch     ToolKind = "search"
	ToolKindExecute    ToolKind = "execute"
	ToolKindThink      ToolKind = "think"
	ToolKindFetch      ToolKind = "fetch"
	ToolKindSwitchMode ToolKind = "switch_mode"
	ToolKindOther      ToolKind = "other"
)

type UnstructuredCommandInput struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Hint string         `json:"hint"`
}

type UntitledMultiSelectItems struct {
	Meta map[string]any        `json:"_meta,omitempty"`
	Enum []string              `json:"enum"`
	Type ElicitationStringType `json:"type"`
}

type WaitForTerminalExitRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

type WaitForTerminalExitResponse struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode int            `json:"exitCode,omitempty"`
	Signal   string         `json:"signal,omitempty"`
}

type WriteTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Content   string         `json:"content"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

type WriteTextFileResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}
