package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

type schema struct {
	Defs map[string]*schemaDef `json:"$defs"`
}

type schemaDef struct {
	Type                 any                   `json:"type"`
	Format               string                `json:"format"`
	Properties           map[string]*schemaDef `json:"properties"`
	Items                *schemaDef            `json:"items"`
	AdditionalProperties any                   `json:"additionalProperties"`
	Required             []string              `json:"required"`
	Ref                  string                `json:"$ref"`
	AnyOf                []*schemaDef          `json:"anyOf"`
	AllOf                []*schemaDef          `json:"allOf"`
	Const                any                   `json:"const"`
	Enum                 []any                 `json:"enum"`
}

type metaFile struct {
	Version       int               `json:"version"`
	AgentMethods  map[string]string `json:"agentMethods"`
	ClientMethods map[string]string `json:"clientMethods"`
}

func main() {
	moduleRoot := flag.String("root", ".", "module root")
	flag.Parse()

	root := filepath.Join(*moduleRoot, "testdata", "acp-schema")
	sch := readJSON[schema](filepath.Join(root, "schema.json"))
	meta := readJSON[metaFile](filepath.Join(root, "meta.json"))

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate ./acp; DO NOT EDIT.\n\n")
	buf.WriteString("package acp\n\n")
	buf.WriteString("import \"encoding/json\"\n\n")
	fmt.Fprintf(&buf, "const ProtocolVersionNumber = %d\n\n", meta.Version)
	writeMethods(&buf, "Agent", meta.AgentMethods)
	writeMethods(&buf, "Client", meta.ClientMethods)

	names := make([]string, 0, len(sch.Defs))
	for name := range sch.Defs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		writeDef(&buf, name, sch.Defs[name])
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		_ = os.WriteFile(filepath.Join("acp", "types_gen.go.bad"), buf.Bytes(), 0o644)
		log.Fatalf("format generated code: %v", err)
	}
	if err := os.WriteFile(filepath.Join(*moduleRoot, "acp", "types_gen.go"), out, 0o644); err != nil {
		log.Fatal(err)
	}
}

func readJSON[T any](path string) T {
	b, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	var v T
	if err := json.Unmarshal(b, &v); err != nil {
		log.Fatalf("%s: %v", path, err)
	}
	return v
}

func writeMethods(buf *bytes.Buffer, side string, methods map[string]string) {
	keys := make([]string, 0, len(methods))
	for key := range methods {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	fmt.Fprintf(buf, "const (\n")
	for _, key := range keys {
		fmt.Fprintf(buf, "\t%sMethod%s = %q\n", side, exportedName(key), methods[key])
	}
	fmt.Fprintf(buf, ")\n\n")
}

func writeDef(buf *bytes.Buffer, name string, def *schemaDef) {
	goName := exportedName(name)
	if isObject(def) {
		fmt.Fprintf(buf, "type %s struct {\n", goName)
		required := make(map[string]bool, len(def.Required))
		for _, key := range def.Required {
			required[key] = true
		}

		keys := make([]string, 0, len(def.Properties))
		for key := range def.Properties {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			prop := def.Properties[key]
			if prop.Const != nil {
				continue
			}
			fieldType := goType(prop, true)
			if !required[key] && shouldPointer(prop, fieldType) {
				fieldType = "*" + fieldType
			}
			tag := key
			if !required[key] {
				tag += ",omitempty"
			}
			fmt.Fprintf(buf, "\t%s %s `json:%q`\n", exportedName(key), fieldType, tag)
		}
		fmt.Fprintf(buf, "}\n\n")
		return
	}

	if enumType, values := enum(def); enumType != "" {
		fmt.Fprintf(buf, "type %s %s\n\n", goName, enumType)
		if len(values) > 0 {
			fmt.Fprintf(buf, "const (\n")
			for _, value := range values {
				fmt.Fprintf(buf, "\t%s%s %s = %s\n", goName, exportedName(fmt.Sprint(value)), goName, literal(value))
			}
			fmt.Fprintf(buf, ")\n\n")
		}
		return
	}

	fmt.Fprintf(buf, "type %s %s\n\n", goName, goType(def, false))
}

func isObject(def *schemaDef) bool {
	if def == nil {
		return false
	}
	if len(def.Properties) > 0 {
		return true
	}
	return hasType(def, "object") && len(def.AnyOf) == 0 && len(def.AllOf) == 0
}

func enum(def *schemaDef) (string, []any) {
	values := append([]any(nil), def.Enum...)
	for _, variant := range def.AnyOf {
		if variant.Const != nil {
			values = append(values, variant.Const)
		}
	}
	if len(values) == 0 {
		return "", nil
	}
	switch values[0].(type) {
	case string:
		return "string", values
	case float64:
		return "int", values
	default:
		return "", nil
	}
}

func goType(def *schemaDef, field bool) string {
	if def == nil {
		return "json.RawMessage"
	}
	if def.Ref != "" {
		return refName(def.Ref)
	}
	if len(def.AllOf) == 1 {
		return goType(def.AllOf[0], field)
	}
	if len(def.AnyOf) > 0 {
		nonNull := make([]*schemaDef, 0, len(def.AnyOf))
		for _, variant := range def.AnyOf {
			if !hasType(variant, "null") {
				nonNull = append(nonNull, variant)
			}
		}
		if len(nonNull) == 1 {
			t := goType(nonNull[0], field)
			if field && nullable(def) && !strings.HasPrefix(t, "[]") && !strings.HasPrefix(t, "map[") && t != "json.RawMessage" && t != "any" {
				return "*" + t
			}
			return t
		}
		return "json.RawMessage"
	}
	if def.Items != nil || hasType(def, "array") {
		return "[]" + goType(def.Items, false)
	}
	if hasType(def, "object") {
		if def.AdditionalProperties != nil && len(def.Properties) == 0 {
			return "map[string]any"
		}
		return "json.RawMessage"
	}
	if hasType(def, "string") {
		return "string"
	}
	if hasType(def, "integer") {
		switch def.Format {
		case "uint16":
			return "uint16"
		case "int32":
			return "int32"
		case "int64":
			return "int64"
		default:
			return "int"
		}
	}
	if hasType(def, "number") {
		return "float64"
	}
	if hasType(def, "boolean") {
		return "bool"
	}
	if hasType(def, "null") {
		return "json.RawMessage"
	}
	return "json.RawMessage"
}

func shouldPointer(def *schemaDef, typ string) bool {
	if strings.HasPrefix(typ, "*") || strings.HasPrefix(typ, "[]") || strings.HasPrefix(typ, "map[") {
		return false
	}
	if typ == "json.RawMessage" || typ == "any" || typ == "string" || typ == "bool" || typ == "int" || typ == "int32" || typ == "int64" || typ == "uint16" || typ == "float64" {
		return false
	}
	if def.Ref != "" {
		return true
	}
	if len(def.AllOf) == 1 && def.AllOf[0].Ref != "" {
		return true
	}
	if len(def.AnyOf) > 0 {
		for _, variant := range def.AnyOf {
			if variant.Ref != "" {
				return true
			}
			if len(variant.AllOf) == 1 && variant.AllOf[0].Ref != "" {
				return true
			}
		}
	}
	return false
}

func hasType(def *schemaDef, want string) bool {
	if def == nil {
		return false
	}
	switch t := def.Type.(type) {
	case string:
		return t == want
	case []any:
		for _, item := range t {
			if s, ok := item.(string); ok && s == want {
				return true
			}
		}
	}
	return false
}

func nullable(def *schemaDef) bool {
	if hasType(def, "null") {
		return true
	}
	for _, variant := range def.AnyOf {
		if hasType(variant, "null") {
			return true
		}
	}
	return false
}

func refName(ref string) string {
	return exportedName(strings.TrimPrefix(ref, "#/$defs/"))
}

var wordRE = regexp.MustCompile(`[A-Za-z0-9]+`)

func exportedName(s string) string {
	s = strings.NewReplacer("_", " ", "-", " ", "/", " ", ".", " ").Replace(s)
	s = regexp.MustCompile(`([a-z0-9])([A-Z])`).ReplaceAllString(s, "$1 $2")
	s = regexp.MustCompile(`([A-Z]+)([A-Z][a-z])`).ReplaceAllString(s, "$1 $2")
	parts := wordRE.FindAllString(s, -1)
	if len(parts) == 0 {
		return "Value"
	}
	var out strings.Builder
	for _, part := range parts {
		upper := strings.ToUpper(part)
		switch upper {
		case "ID", "URL", "URI", "JSON", "RPC", "HTTP", "SSE", "MCP", "ACP", "FS":
			out.WriteString(upper)
			continue
		}
		runes := []rune(strings.ToLower(part))
		runes[0] = unicode.ToUpper(runes[0])
		out.WriteString(string(runes))
	}
	return out.String()
}

func literal(v any) string {
	switch x := v.(type) {
	case string:
		return fmt.Sprintf("%q", x)
	case float64:
		return fmt.Sprintf("%d", int(x))
	default:
		return "0"
	}
}
